uploads = []
generated = []

[[outputs]]
id = "oElZnMKDe-YbBDogh2xMi"
uri = "file://omniverseos-changes.tar.gz"
type = "unspecified"
title = "OmniverseOS — All Changes (tar.gz)"

[[outputs]]
id = "IKBbqyZ6WEcmAlkCOLOUt"
uri = "file://omniverseos-all-changes.tar.gz"
type = "unspecified"
title = "OmniverseOS — Complete Polish (15 files, 53.5 KB)"
