uploads = []
generated = []

[[outputs]]
id = "7ZrFw58gWnO9iPouK6FJk"
uri = "file://omniverse-responsive-changes.zip"
type = "unspecified"
title = "OmniverseOS Responsive Changes — all 24 modified files"
